### ISSUE TITLE
make failure

### ISSUE THREAD

**Issue by lummm** [facebook/wangle#49] opened 2016-05-20 20:35 UTC
Building on Arch Linux with 8Gb of ram, no swap.  Can Acceptor.o require 8Gb to compile?

[  1%] Building CXX object CMakeFiles/wangle.dir/acceptor/Acceptor.cpp.o
virtual memory exhausted: Cannot allocate memory
CMakeFiles/wangle.dir/build.make:62: recipe for target 'CMakeFiles/wangle.dir/acceptor/Acceptor.cpp.o' failed
make[2]: *** [CMakeFiles/wangle.dir/acceptor/Acceptor.cpp.o] Error 1
CMakeFiles/Makefile2:484: recipe for target 'CMakeFiles/wangle.dir/all' failed
make[1]: *** [CMakeFiles/wangle.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by snarkmaster** [comment] 2016-05-23 22:06
That's surprising to me -- it shouldn't, at least I have previously built in Ubuntu VMs with 1.5GB of RAM, but your compiler could have a bug.

I would recommend that you try debugging the usual way:

1) Use `top`, `htop`, `atop`, or `ps` to identify memory users on your system.

2) Try running just that one C++ compile under `/usr/bin/time`, as per man page, it will print out memory usage:

```
           %Uuser %Ssystem %Eelapsed %PCPU (%Xtext+%Ddata %Mmax)k
           %Iinputs+%Ooutputs (%Fmajor+%Rminor)pagefaults %Wswaps
```

If the compile indeed consumes inordinate amounts of memory, please post more details here.

To even have a chance of reproducing, I'd need:
 - the compiler and glibc versions
 - the SHA1s of the wangle & folly repos that you are building

**Comment by djwatson** [comment] 2016-06-16 13:46
Closing as dupe of #51

**Closed by djwatson** 2016-06-16 13:46 UTC
